### ISSUE TITLE
Connection Reset Error:

### ISSUE THREAD

**Issue by GivanTsai** [AmitMY/chimera#20]
When I run the **server/server.py** script, some errors happen. How can I fix it?

File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dbpedia.org', port=443): Max retries exceeded with url: /data/ACF_Fiorentina.json (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server/server.py", line 95, in <module>
    res = MainPipeline.mutate({"config": main_config}).execute(dataset_name, cache_name=dataset_name)
  File "/home/featurize/chimera/utils/pipeline.py", line 148, in execute
    x_params=x_params.union(params), previous_name=pn)
  File "/home/featurize/chimera/utils/pipeline.py", line 148, in execute
    x_params=x_params.union(params), previous_name=pn)
  File "/home/featurize/chimera/utils/pipeline.py", line 154, in execute
    params[qi.key] = qi.method(params, x_params)
  File "/home/featurize/chimera/process/pre_process.py", line 12, in <lambda>
    CorpusPreProcessPipeline.enqueue("entities", "Describe entities", lambda f, _: f["spelling"].copy().describe_entities())
  File "/home/featurize/chimera/data/WebNLG/reader.py", line 187, in describe_entities
    ps = pronouns(ent)
  File "/home/featurize/chimera/utils/dbpedia.py", line 63, in pronouns
    dbpedia = get_dbpedia_entity(entity)
  File "/home/featurize/chimera/utils/dbpedia.py", line 35, in get_dbpedia_entity
    r = requests.get(url=DBPEDIA + 'data/' + entity + '.json')
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='dbpedia.org', port=443): Max retries exceeded with url: /data/ACF_Fiorentina.json (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))

**Comment by AmitMY** [comment]
It says that it can't connect to `dbpedia.org`.
I assume this comes from the use of this function:
https://github.com/AmitMY/chimera/blob/dfd804e8dc1d7eebbfc3092d7d6d99654c06464b/utils/dbpedia.py#L62

To test if that is the problem, replace the function's body with `return []`

**Comment by GivanTsai** [comment]
> It says that it can't connect to `dbpedia.org`.
> I assume this comes from the use of this function:
> https://github.com/AmitMY/chimera/blob/dfd804e8dc1d7eebbfc3092d7d6d99654c06464b/utils/dbpedia.py#L62
> 
> To test if that is the problem, replace the function's body with `return []`

It doesn't make sense. I think there are something wrong in the setup.sh. Do you run the whole project successfully in your local machine now?

**Comment by AmitMY** [comment]
Did you modify the part I mentioned and something else failed? If so, what is the error.
If not, this is the place to modify.

I did not try to run the entire project on my local machine in the past 6 months or so.

**Comment by GivanTsai** [comment]
> Did you modify the part I mentioned and something else failed? If so, what is the error.
> If not, this is the place to modify.
> 
> I did not try to run the entire project on my local machine in the past 6 months or so.

When I run ./setup.sh directly, some errors occurred on installing torchtext package. I have tried the method you suggested.
