### ISSUE TITLE
Problem loading the data.vocab.pt

### ISSUE THREAD

**Issue by SilvesterYu** [AmitMY/chimera#24]
Hi! I'm having trouble loading the data checkpoints. 

The specific output and error are:

 WebNLG
   Pre-process training data
     Training Set
      corpus           Read Corpus                      0:00:00.000065
      graphify         RDF to Graph                     0:00:00.000024
      spelling         Fix Spelling                     0:00:00.000018
      entities         Describe entities                0:00:00.000025
      match-ents       Match Entities                   0:00:00.000042
      match-plans      Match Plans                      0:00:00.000020
      tokenize         Tokenize Plans & Sentences       0:00:00.000017
      to-json          Export in a readable format      0:00:00.000022
     Dev Set
      corpus           Read Corpus                      0:00:00.000042
      graphify         RDF to Graph                     0:00:00.000019
      spelling         Fix Spelling                     0:00:00.000019
      entities         Describe entities                0:00:00.000020
      match-ents       Match Entities                   0:00:00.000020
      match-plans      Match Plans                      0:00:00.000019
      tokenize         Tokenize Plans & Sentences       0:00:00.000018
      to-json          Export in a readable format      0:00:00.000016
   Train Planner
    planner      Learn planner           0:00:00.000036
   Train Model
    model            Initialize OpenNMT             0:00:00.000034
    expose           Expose Train Data              0:00:00.000017
    pre-process      Pre-process Train and Dev      0:00:00.000018
    train            Train model                    EXEC /home/ubuntu/miniconda3/envs/env_pytorch/bin/python /home/ubuntu/chimera/model/../libs/OpenNMT/train.py -train_steps 30000 -save_checkpoint_steps 1000 -batch_size 16 -word_vec_size 300 -feat_vec_size 10 -feat_merge concat -layers 3 -copy_attn -position_encoding -data /tmp/tmpz79gzk1g/data -save_model /tmp/tmpo6y8o6dz/ -world_size 1 -gpu_ranks 0

------------------------------------------------ (so the error happened here) -------------------------------------------------------

Traceback (most recent call last):
  File "/home/ubuntu/chimera/model/../libs/OpenNMT/train.py", line 109, in <module>
    main(opt)
  File "/home/ubuntu/chimera/model/../libs/OpenNMT/train.py", line 39, in main
    single_main(opt, 0)
  File "/home/ubuntu/chimera/libs/OpenNMT/onmt/train_single.py", line 63, in main
    vocab = torch.load(opt.data + '.vocab.pt')
  File "/home/ubuntu/miniconda3/envs/env_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/miniconda3/envs/env_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

--------------------------------------- (the error is above)-------------------------------------

Could you kindly provide some help? I would be very grateful!

**Comment by AmitMY** [comment]
did it successfully create a vocabulary file in `/tmp/tmpz79gzk1g/data`?

If there is no persistent `tmp` storage on your sever, perhaps you should export `TMPDIR` to some other directory.

**Comment by SilvesterYu** [comment]
Yes, the vocabulary file is created in /tmp. The files are below:
<img width="412" alt="1646918916(1)" src="https://user-images.githubusercontent.com/74582280/157671976-3e00bf64-5fe3-4abb-a60e-9c6471ff7fe5.png">
Also, inside the data.vocab.pt:
<img width="658" alt="8d8e2468b594dd5d299f53485bc35a9" src="https://user-images.githubusercontent.com/74582280/157672213-c3c9c927-97af-4c01-a791-7ea08a0d3408.png">
